#!/bin/bash
a=(3 5 6 10 6)
b=(6 4 5 12)
c=(14 7 5 7)

  for x in "${a[@]}"; do
  for y in "${b[@]}"; do
    if [ $x = $y ]; then
    z[${#z[@]}]=$x
   fi
  done
 done
  for i in "${c[@]}"; do
  for k in "${z[@]}"; do
    if [ $i = $k ];then
      j[${#j[@]}]=$i
     fi
    done
   done
   
   echo ${j[@]}
